// Code generated by mockery 2.7.4. DO NOT EDIT.

package business

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/wizelineacademy/academy-go-q12021/model"
)

// MockPokemonBusiness is an autogenerated mock type for the IPokemonBusiness type
type MockPokemonBusiness struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *MockPokemonBusiness) GetAll() ([]model.Pokemon, error) {
	ret := _m.Called()

	var r0 []model.Pokemon
	if rf, ok := ret.Get(0).(func() []model.Pokemon); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Pokemon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockPokemonBusiness) GetByID(id int) (*model.Pokemon, error) {
	ret := _m.Called(id)

	var r0 *model.Pokemon
	if rf, ok := ret.Get(0).(func(int) *model.Pokemon); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pokemon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreByID provides a mock function with given fields: id
func (_m *MockPokemonBusiness) StoreByID(id int) (*model.Pokemon, error) {
	ret := _m.Called(id)

	var r0 *model.Pokemon
	if rf, ok := ret.Get(0).(func(int) *model.Pokemon); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pokemon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
